-- Supabase setup (OPTIONAL).
-- The app runs with built-in mock data if you skip this entirely.
-- Run this in the Supabase SQL editor to use a real database.

create table if not exists applications (
  id bigint generated by default as identity primary key,
  passport text not null,
  vfs_ref text not null,
  status text not null check (status in ('Under Process', 'Approved', 'Rejected')),
  applicant text,
  type text default 'Visa Application',
  permit_number text,
  valid_until date,
  submitted date default now()
);

create table if not exists users (
  email text primary key,
  type text not null default 'standard' check (type in ('premium', 'standard')),
  created_at timestamptz default now()
);

-- Migration: if the users table was created before user categories existed,
-- add the column. Safe to run repeatedly.
alter table users
  add column if not exists type text not null default 'standard';

-- Migration: add permit columns to an existing applications table.
alter table applications
  add column if not exists permit_number text;
alter table applications
  add column if not exists valid_until date;

-- Seed data
insert into applications (passport, vfs_ref, status, applicant, permit_number, valid_until, submitted) values
  ('P12345', 'VFS001', 'Under Process', 'John Doe', 'PRM-2026-0001', '2027-05-12', '2026-05-12'),
  ('P99999', 'VFS002', 'Approved', 'Jane Smith', 'PRM-2026-0002', '2028-04-28', '2026-04-28'),
  ('P55555', 'VFS003', 'Rejected', 'Michael Brown', null, null, '2026-05-01')
on conflict do nothing;

-- Backfill the new columns on rows that were seeded before they existed.
update applications set permit_number = 'PRM-2026-0001', valid_until = '2027-05-12'
  where passport = 'P12345' and vfs_ref = 'VFS001';
update applications set permit_number = 'PRM-2026-0002', valid_until = '2028-04-28'
  where passport = 'P99999' and vfs_ref = 'VFS002';

-- Premium users are created out of band by an admin. They track and view
-- status for free. Standard users (self sign-ups) pay per record searched.
insert into users (email, type) values
  ('premium@vfs.com', 'premium')
on conflict do nothing;

-- For this prototype the anon key reads applications directly.
-- Enable RLS with appropriate policies before any production use.
alter table applications enable row level security;
create policy "allow read applications"
  on applications for select using (true);

alter table users enable row level security;
create policy "allow upsert users"
  on users for insert with check (true);
create policy "allow read users"
  on users for select using (true);